---
title: Credntia
timezone: UTC
collections:
  blog:
    title: Posts
    output: true
    permalink: blog/:path/
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
copyright: "© 2017 Credntia LLC"
email: info@credntia.com
description: 'We''re an identity company with a focus on access control.

'
baseurl: ''
url: http://credntia.com
port: 8000
twitter_username: credntia
github_username: credntia
header_pages:
- index.md
google_analytics:
  prod_key: UA-82383119-1
  staging_key: test
intercom:
  prod_key: r4yeksa5
  staging_key: gs1pm8wa
markdown: kramdown
gems:
- jekyll-feed
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- old
