---
title: Credntia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://credntia.com
email: info@credntia.com
copyright: "© 2017 Credntia LLC"
description: 'We''re an identity company with a focus on access control.

'
google_analytics:
  prod_key: UA-82383119-1
  staging_key: test
intercom:
  prod_key: r4yeksa5
  staging_key: gs1pm8wa
social:
  facebook: credntia
  twitter: credntia
  instagram: credntiaapp
  medium: credntia
  linked-in: credntia
  angel: credntia
  github: credntia
defaults:
- scope:
    path: ''
    type: pages
    permalink: "/:title/"
  values:
    layout: page
- scope:
    path: ''
    type: posts
    permalink: "/blog/:title/"
  values:
    layout: post
baseurl:
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- old
gems:
- jekyll-feed
- jekyll-redirect-from
markdown: kramdown
permalink: "/blog/:title/"
port: 8000
whitelist:
- jekyll-redirect-from
