---
title: Credntia
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  team_members:
    title: Team Members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    subtitle: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    subtitle: 
    author: 
- scope:
    path: ''
    type: team_members
  values:
    permalink: "/team/:title/"
    layout: team_member
    team_title: 
    image: 
url: http://credntia.com
email: info@credntia.com
description: 'We''re an identity company with a focus on access control.

'
copyright: "© 2017 Credntia LLC"
google_analytics:
  tracking_id: UA-82383119-1
intercom:
  prod_key: r4yeksa5
  staging_key: gs1pm8wa
baseurl: 
gems:
- jekyll-feed
- jekyll-redirect-from
markdown: kramdown
permalink: pretty
port: 8000
